// @flow
export const ADD_TODO: "ADD_TODO" = "ADD_TODO"
export const TOGGLE_TODO: "TOGGLE_TODO" = "TOGGLE_TODO"
export const RECEIVE_TODOS: "RECEIVE_TODOS" = "RECEIVE_TODOS"
export const REQUEST_TODOS: "REQUEST_TODOS" = "REQUEST_TODOS"