// @flow
export const ADD_TODO_REQUEST: "ADD_TODO_REQUEST" = "ADD_TODO_REQUEST"
export const ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS" = "ADD_TODO_SUCCESS"

export const TOGGLE_TODO_REQUEST: "TOGGLE_TODO_REQUEST" = "TOGGLE_TODO_REQUEST"
export const TOGGLE_TODO_SUCCESS: "TOGGLE_TODO_SUCCESS" = "TOGGLE_TODO_SUCCESS"

export const FETCH_TODOS_SUCCESS: "FETCH_TODOS_SUCCESS" = "FETCH_TODOS_SUCCESS"
export const FETCH_TODOS_REQUEST: "FETCH_TODOS_REQUEST" = "FETCH_TODOS_REQUEST"
export const FETCH_TODOS_FAIL: "FETCH_TODOS_FAIL" = "FETCH_TODOS_FAIL"